create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  email text not null,
  avatar_url text,
  body text not null check (char_length(trim(body)) > 0),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists messages_created_at_idx
  on public.messages (created_at asc);

alter table public.messages enable row level security;

drop policy if exists "Authenticated users can view messages" on public.messages;
create policy "Authenticated users can view messages"
on public.messages
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert messages" on public.messages;
create policy "Authenticated users can insert messages"
on public.messages
for insert
to authenticated
with check (auth.uid() = user_id);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end
$$;
